line-length = 100
target-version = "py311"

[lint]
select = ["E", "F", "W", "I", "UP", "B", "C4"]
ignore = ["B008"]

[lint.per-file-ignores]
"modules/__init__.py" = ["F401"]
"tests/*" = ["E402"]
"scripts/*" = ["E402"]
